# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "moinmoin"
description: > # this means to ignore newlines until "email:"
   备用停车场 - 食用愉快！

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/original.png"

name: 'moinmoin'
author: 'moinmoin'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://diealittle.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: G-8L6CJ7YFVY

# social icons and sharing options
# social:
#   - icon:	twitter
#     url:	https://twitter.com/dirkfabisch
#     desc: Follow me on lofter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#   - icon:	github
#     url:	https://github.com/dirkfabisch
#     desc:	Fork me on github
#     share_url:
#     share_title:
#     share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
